# Generated by Django 6.0.1 on 2026-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_choice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
